name: test

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ '3.1', '3.0', '2.7', head ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
        - { os: windows-latest, ruby: head }
        include:
        - { os: windows-latest, ruby: mingw }
        - { os: windows-latest, ruby: mswin }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake test
